### ISSUE TITLE
"startarch" missing

### ISSUE THREAD

**Issue by Jerrytype** [sdrausty/TermuxArch#104]
Today I tried to reinstall Termuxarch by "bash setupTermuxArch.sh".
After "Uncompressing ArchlinuxARM-aarch64-lastest.tar.gz...", "setupTermuxArch.sh v1.6 DONE" shows immediately and terminate. arch/startarch is missing and two additional files showup:
arch/ArchlinuxARM-aarch64-lastest.tar.gz
arch/ArchlinuxARM-aarch64-lastest.tar.gz.md5
others folders like bin/ dev/ etc/ ...  still exist.
So, is the script being removed or something wrong with my installation? I have tried to install in clean Termux and alternative mobile phones, but all have the same problems......

**Comment by sdrausty** [comment]
Try `setupTermuxArch.sh refresh ` which should tidy up the installation.  This error should be resolved at present.

**Comment by Jerrytype** [comment]
It print out "The root directory structure is incorrect; Cannot continue setupTermuxArch.sh"
The folder of /data/data/com.termux/files/home/arch contain:
ArchlinuxARM-aarch64-lastest.tar.gz
ArchlinuxARM-aarch64-lastest.tar.gz.md5
bin boot dev rtc home lib mnt opt proc root run sbin srv sys tmp usr var
"startarch" still missing......

Anyway, thank you for your help!   I really like this project!!

**Comment by sdrausty** [comment]
```
🕙 Uncompressing ./ArchLinuxARM-aarch64-latest.tar.gz…
 🕚 Uncompressing ./ArchLinuxARM-aarch64-latest.tar.gz…
setupTermuxArch.sh ./ArchLinuxARM-aarch64-latest.tar.gz ar v1.6: DONE 🏁
$ 
```
Twas gone
Came right back
Thank you

**Comment by sdrausty** [comment]
`setupTermuxArch.sh refresh` will work for you as well as install from start to finish.  It appears that the error is in Termux Busybox. Reference commit https://github.com/sdrausty/TermuxArch/commit/265fadb336a12871adb2a5edf57b930bb276242b#diff-a8f27a760a6efd68e7e20b3deb5354df

**Comment by Jerrytype** [comment]
Problem solved! Nice work!

**Comment by sdrausty** [comment]
You are welcome!

**Comment by sdrausty** [comment]
The most recent version takes this error into account.  Use `setupTermuxArch.sh refresh` to update your Arch Linux in Termux PRoot.  Should refresh not accomplish its' task, reinstall.
