### ISSUE TITLE
Error while Configuring Arch x86_64 on arm

### ISSUE THREAD

**Issue by WMCB-Tech** [SDRausty/TermuxArch#259]
Hey @SDRausty sorry if you're busy but one more report. so while installing Arch x86_64. everything was good when downloading bootstraps. i entered this command to install arch x86_64:

`./setupTermuxArch q m arch-x86_64`

And i set to manual to change mirrors. after downloading it gives me this error:

```
🕛 > 🕘 Cleaning up installation files: DONE

🕛 > 🕤 Arch Linux in Termux PRoot is installed.  Configuring and updating Arch Linux 📲 
espritfunctions.bash: line 20: ceds[$i]: unbound variable
setupTermuxArch q m arch-qemu 2.0.599: [Exit Signal 1] DONE 🏁
```

Here's the full Transcript/Log: https://pastebin.com/graKnHFB

It does not configure locales, pacman keys, pacman updates, etc.

I tried x86. it does configure. but the Repositories is down and says cannot find db'es when running `pacman -Syu` so i chose x86_64

Sorry for disturbing you but i want to report this so to improve something.

**Comment by SDRausty** [comment]
> Here's the full Transcript/Log:

@WMCB-Tech this directory https://github.com/TermuxArch/docsTermuxArch/tree/master/logging shares log output. Can you please share a PR with full Transcript/Log at https://github.com/TermuxArch/docsTermuxArch/pulls with the log output?

**Comment by SDRausty** [comment]
> tried x86

Thanks for trying @WMCB-Tech; I tried it too. I am amazed you hear that [i386 emulation ](https://github.com/TermuxArch/TermuxArch/issues/25) is doable.  This issue [Implementing QEMU #25](https://github.com/TermuxArch/TermuxArch/issues/25) has more information.

**Comment by WMCB-Tech** [comment]
@SDRausty I run the command `./setupTermuxArch q refresh arch-amd` the it configures though the Repositories are not that yet configured and says error about db'es or databases

**Comment by SDRausty** [comment]
This commit https://github.com/SDRausty/TermuxArch/commit/8673ef1a19ed6f9b8e3618d0cfce128f62bff1bb automates qemu refresh; `setupTermuxArch qemu refresh`.  It also updates contact information for Arch Linux x86 and x86_64 distributions and updates the Arch Linux x86 mirrorlist to the current one.  Thank you for creating the PR @WMCB-Tech 🎶

**Comment by WMCB-Tech** [comment]
@SDRausty x86 Works and configures the repos. which it prompts me to configure it and it configures Flawlessly through the setup procress (though i was getting errors about locales)

Which this is a wonderful result for x86:
![IMG_20201021_144808.jpg](https://user-images.githubusercontent.com/65075766/96683234-7305e180-13ac-11eb-80ee-bbb04884b8da.jpg)

But in x86_64 however. it doesn't prompt me for configuring repos. and still doesn't establish db'es:
![Screenshot_2020-10-21-14-41-38-95.png](https://user-images.githubusercontent.com/65075766/96683370-b2343280-13ac-11eb-8748-4a8f0e4b82be.png)

**Comment by SDRausty** [comment]
> amazed to hear that i386 emulation is doable

> [What is the simplest way to resolve this error without creating and publishing an updated root file system?](https://bbs.archlinux32.org/viewtopic.php?pid=7459#p7459)

**Comment by SDRausty** [comment]
>> amazed to hear that i386 emulation is doable

>> [What is the simplest way to resolve this error without creating and publishing an updated root file system?](https://bbs.archlinux32.org/viewtopic.php?pid=7459#p7459)

Importing the key from this http://archive.archlinux32.org/packages/p/pacman/pacman-5.2.1-1.4-i686.pkg.tar.xz package.

**Comment by SDRausty** [comment]
> x86 Works and configures the repos.

Thank you for confirming @WMCB-Tech.   There is more information about updating and configuration to the newest published version for x86 [here](https://bbs.archlinux32.org/viewtopic.php?id=2982&p=2).

**Comment by SDRausty** [comment]
@WMCB-Tech you might be surprised to know that resolving this `ceds[$i]: unbound variable` made headway today at this [`[16:29~]$ which editor`](https://www.reddit.com/r/termux/comments/jfq7xi/1629_which_editor/) link.

**Comment by WMCB-Tech** [comment]
@SDRausty so the unbound variable opens the editor command

**Comment by SDRausty** [comment]
This fragment of code we are discussing is a relic from on of the earliest publications of TermuxArch, and Termux is still growing with new features that are mainstream in the computer box world for decades now, but are disallowed on Android with upgraded versions.   An answer about how to rewrite the code were discussing that generates this error came in today.  I need to understand what TermuxArch does in Termux to be able to help it grow.  And I just found out important information about how to [here](https://www.reddit.com/r/termux/comments/jfq7xi/1629_which_editor/).

**Comment by SDRausty** [comment]
>  i tried to type `./setupTermuxArch refresh` arch-amd and gives me vpid errors in proot

Please try the `setupTermuxArch refresh` command again as the mirror list and resolve configuration is updated now with more recent commits.  The packages should synchronize properly.  They will NOT install automatically as the key for pacman-5.2.1-1.4-i686.pkg.tar.xz is still manually imported:
>>> [What is the simplest way to resolve this error without creating and publishing an updated root file system?](https://bbs.archlinux32.org/viewtopic.php?pid=7459#p7459)

This manual method presented in detail at https://bbs.archlinux32.org/viewtopic.php?pid=7459#p7459 has not been tested on Android smartphone. Would you like to test it @WMCB-Tech?

**Comment by WMCB-Tech** [comment]
@SDRausty sure

**Comment by SDRausty** [comment]
> unbound variable

The `$EDITOR` environmental variable will probably be tested first.  If it is unbound, the the `editor` command should probably be next.  What do you think?

**Comment by SDRausty** [comment]
The relic code will become obsolete.  On the other hand this code can be expanded to assist the user in installing an editor of choice in Termux.

**Comment by SDRausty** [comment]
> @SDRausty sure

If you are successful in updating @WMCB-Tech please share [here](https://bbs.archlinux32.org/viewtopic.php?pid=7460#p7460) too if you can.  If you run into stumbling blocks [this same source the best one to ask for help](https://bbs.archlinux32.org/viewtopic.php?pid=7460#p7460) in resolving Arch Linux 32 x86 in our modern day Android emulated environment.

**Comment by SDRausty** [comment]
> key for pacman-5.2.1-1.4-i686.pkg.tar.xz is still manually imported.

[`printf "\\\\e[0;32m%s\\\\n%s\\\\n%s\\\\e[1;32m%s\\\\e[0m\\\\n" "Paths that can be followed after building 'yay' are 'yay cmatrix' which builds matrix screensavers.  The commands 'yay pikaur|pikaur-git|tpac' build more aur installers which can also be used to download aur repositories and build packages like with 'yay' in your Android smartphone, tablet, wearable and more.  Did you know that 'android-studio' is available with the command 'yay android'?" "If you have trouble importing keys, this command 'gpg --keyserver keyserver.ubuntu.com --recv-keys 71A1D0EFCFEB6281FD0437C71A1D0EFCFEB6281F' might help.  Change the number to the number of the key being imported." "Building and installing yay: " "DONE 🏁"`](https://github.com/SDRausty/TermuxArch/blob/master/archlinuxconfig.bash#L720)

**Comment by WMCB-Tech** [comment]
@SDRausty this is the setup process that i gone through and works fine as intended:
![Screenshot_2020-10-22-14-17-02-95.png](https://user-images.githubusercontent.com/65075766/96832494-6d260400-1471-11eb-93f1-cfcd6b1cdcaa.png)

![Screenshot_2020-10-22-14-17-02-95.png](https://user-images.githubusercontent.com/65075766/96832516-7616d580-1471-11eb-837a-d1fb97640354.png)

**Comment by SDRausty** [comment]
@WMCB-Tech these screenshots are great!  Thank you!  Can you make a PR at the images submodule [(`cat docs/.gitmodules`)](https://github.com/TermuxArch/imgsTermuxArch/pulls) with them please?

**Comment by SDRausty** [comment]
> answer about how to rewrite the code we are discussing that generates this error came in today


https://github.com/SDRausty/TermuxArch/issues?q=is%3Aissue+ceds

**Comment by SDRausty** [comment]
> become obsolete. On the other hand this code can be recycled and expanded to assist the user

`$ f -w ceds *h|wc -l`
`14`

**Comment by SDRausty** [comment]
The error `ceds[$i]: unbound variable` is resolved again.  This time this https://github.com/SDRausty/TermuxArch/commit/68631a280d11872dd35d02f3b808311cde74164f commit is the assisting commit, and comment, "[[16:29~]$ which editor](https://www.reddit.com/r/termux/comments/jfq7xi),” was one of the assisting discussions including this issue;  Thank you @WMCB-Tech very much.

**Comment by WMCB-Tech** [comment]
You're welcome @SDRausty

**Comment by SDRausty** [comment]
@WMCB-Tech one more thank you for you;  This time for helping to enable more TermuxArch documentation for us with this https://github.com/TermuxArch/imgsTermuxArch/commit/5bd259040b92b90d785805a3def3fb2337a4d4ea commit!  

This commit would not have been possible without the images you contributed regarding the issue we are discusding and working on here.  These images are now published courtesy of GitHub, and are also available with the  command [`cat docs/.gitmodules`](https://github.com/TermuxArch/imgsTermuxArch) run in the root directory of [this](https://github.com/SDRausty/TermuxArch) cloned git repositories which have had the submodules populated.   

The command [`pullTermuxArchSubmodules.bash`](https://github.com/SDRausty/TermuxArch/blob/master/pullTermuxArchSubmodules.bash) can be used in order to populate all the nested TermuxArch submodules the newest published versions.

**Comment by SDRausty** [comment]
Can you please confirm whether this error still persists on arm architecture?

```
espritfunctions.bash: line 20: ceds[$i]: unbound variable
setupTermuxArch q m arch-qemu 2.0.599: [Exit Signal 1] DONE 🏁
```
It should be sufficient to run these commands to see whether it does crop up like it used to from time to time:
```
mkdir ~/tmp ; cd ~/tmp
curl -O https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch
bash setupTermuxArch r m [arch-qemu]
```

**Comment by WMCB-Tech** [comment]
@SDRausty No it does not. but i get this error on both x86 and x86_64 after downloading:

![Screenshot_2020-10-23-13-46-28-84.png](https://user-images.githubusercontent.com/65075766/96960985-467dd100-1536-11eb-8b07-88eca72b12a0.png)

However re-runing the command fixes and both extracts and configures the x86 Environment. x86_64 however still getting an error about variables

**Comment by SDRausty** [comment]
@WMCB-Tech thank you for checking and sharing your results.  Can you please recheck as the latest [commits](https://github.com/SDRausty/TermuxArch/commits/master) should resolve you just shared?

**Comment by SDRausty** [comment]
This commit https://github.com/SDRausty/TermuxArch/commit/95c9f62e31896e02e83e1954248057ca02c53cff attempts to automate x86 configuration.  @WMCB-Tech stated:
> it's fixed when removing the db lock and refresh it

This is the best result so far with `setupTermuxArch qemu`:
```
Disabling key 66BD74A036D522F51DD70A3C7F2A16726521E06D...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   6  signed:  62  trust: 0-, 0q, 0n, 6m, 0f, 0u
gpg: depth: 2  valid:  62  signed:   6  trust: 62-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2021-10-23
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key B1117BC1094EA6E9: public key "Erich Eckner <deep42thought@archlinux32.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
resolving dependencies...
looking for conflicting packages...

Packages (2) archlinux32-keyring-20200408-1.0  pacman-5.2.2-1.0

Total Download Size:   0.87 MiB
Total Installed Size:  4.53 MiB
Net Upgrade Size:      0.08 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 archlinux32-keyring...    32.3 KiB  1196K/s 00:00 [####################] 100%
 pacman-5.2.2-1.0-i686    853.5 KiB  19.4M/s 00:00 [####################] 100%
(2/2) checking keys in keyring                     [####################] 100%
downloading required keys...
:: Import PGP key 4096R/5FDCA472AB93292BC678FD59255A76DB9A12601A, "Erich Eckner (just to sign arch packages) <arch@eckner.net>", created: 2018-04-09? [Y/n]
(2/2) checking package integrity                   [####################] 100%
error: archlinux32-keyring: signature from "Erich Eckner (just to sign arch packages) <arch-packages@eckner.net>" is unknown trust
:: File /var/cache/pacman/pkg/archlinux32-keyring-20200408-1.0-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
```
What other steps did you use?

**Comment by WMCB-Tech** [comment]
@SDRausty same as that step you did

**Comment by SDRausty** [comment]
Thank you for replying @WMCB-Tech if x86_64 is okay, I think this issue can be closed;  How about you?

**Comment by WMCB-Tech** [comment]
Sure @SDRausty i could close it

**Comment by SDRausty** [comment]
Do you see any reasons why this issue should remain open?  If not, it's okay to close it.

**Comment by WMCB-Tech** [comment]
@SDRausty Oh. yeah. i should close it. i was busy

**Comment by SDRausty** [comment]
@WMCB-Tech thank you for closing this issue; you are welcome to take part regarding Arch Linux 32 in PRoot  with emulation [here](https://github.com/TermuxArch/TermuxArch/issues/25).
