### ISSUE TITLE
Generated script signal 1 near or at line number 453 by 'cp'!

### ISSUE THREAD

**Issue by Talmio216** [SDRausty/TermuxArch#290]
Since today, the script finishes its work in seconds and seems to not actually download any rootfs file. However, it tries to `cp` it into the `~/arch` folder and fails due to a "missing operand". 

```
Adjusting ownership and permissions...

 🕛 > 🕦 File startarch copied to /data/data/com.termux/files/usr/bin.

 🕛 > 🕝 Detected Android arm64-v8a 7.0 operating system;  Install architecture is set to arm64-v8a.

 🕛 > 🕒 Activating termux-wake-lock: DONE  

cp ArchLinuxARM-aarch64-latest.tar.gz* /data/data/com.termux/files/home/arch

cp: missing destination file operand after '/data/data/com.termux/files/home/arch'
Try 'cp --help' for more information.

 TermuxArch WARNING:  Generated script signal 1 near or at line number 453 by 'cp'!
```
If I run `startarch`, the result is so:
```
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/arch, cwd = /root, $PATH=(null))
fatal error: see `proot --help`.
```
Tested on three devices with different CPUs and Android versions, with the same result: 
* Xiaomi Redmi Note 4X (Android 7.0, aarch64), log [here](https://github.com/SDRausty/TermuxArch/files/7964998/setupTermuxArchSysInfo8743.log);
* Lenovo Tab 2 A7-30DC (Android 6.0.1 / LineageOS 13, armv7l);
* ASUS MemoPad 7 ME70CX (Android 5.0, i686).

Also, there seems to be a minor error in the `knownconfigurations.bash` file, line 91. It happens after the integrity checking:

* `knownconfigurations.bash: line 91: [[: 7.0: syntax error: invalid arithmetic operator (error token is ".0")`
* `knownconfigurations.bash: line 91: [[: 6.0.1: syntax error: invalid arithmetic operator (error token is ".0.1")`
* `knownconfigurations.bash:` line 91: [[: 5.0: syntax error: invalid arithmetic operator (error token is ".0")`

On the first two devices, the installation proceeds despite the error, failing only after the wake-lock activation as shown in the first log fragment. However, it completely stops the script from working on the MemoPad, which also gives the following error: `maintenanceroutines.bash: line 187: USSPACE: unbound variable`.

**Comment by SDRausty** [comment]
>the script finishes its work in seconds

Thank you for sharing this error.  The critical one should be fixed with the most recent commits;  Can you please try once more and share the output again?

**Comment by SDRausty** [comment]
>`cp: missing destination file operand after '/data/data/com.termux/files/home/arch'
Try 'cp --help' for more information.`

I cannot reproduce this error at present; @Talmio216 is this error still still present on your device?

**Comment by Talmio216** [comment]
It works, thank you very much! Installed the system successfully on both devices (the phone and the tablet). Sorry for not being online for a while. 
I also checked the old Asus tablet (the one with i686 CPU) about two days ago. The `unbound variable` error persisted there. However, it may be due to the state of the device (like the old Android version), not the script itself.

**Comment by SDRausty** [comment]
Thank you for helping @Talmio216 🎵 🎶 

> old Asus tablet (the one with i686 CPU) about two days ago. The unbound variable error 

Can you give a little more information about `maintenanceroutines.bash: line 187: USSPACE: unbound variable` please?

If you have a lot of information to share about this error; you are welcome to share [PR text output here](https://github.com/TermuxArch/docsTermuxArch/pulls) and [PR screenshots output here](https://github.com/TermuxArch/imgsTermuxArch/pulls).

The command `setupTermuxArch b` might give us the information that we desire in order to resolve this error.  After running the command and `cd ~/TermuxArchBloom`, please edit L#6 in file `setupTermuxArch` like this `set -Eeuox pipefail` by adding an x and saving the file. 

After the modified script completes, please share all the relevant crash information.  A cache directory can be used to save bandwidth on subsequent installations.

My hunch is this error is related to system architecture names; e.g. x86_64, x86-64 and similar.  Making the font size very small before running the modified script might help as there will be a lot of output.

**Comment by Talmio216** [comment]
> The command `setupTermuxArch b` might give us the information that we desire in order to resolve this error. After running the command and `cd ~/TermuxArchBloom`, please edit L#6 in file `setupTermuxArch` like this `set -Eeuox pipefail` by adding an x and saving the file.

Bloom mode setup log: [bloom-setup.txt](https://github.com/SDRausty/TermuxArch/files/8027114/bloom-setup.txt)
The result of the modified script run: [termuxarch-asus-log.txt](https://github.com/SDRausty/TermuxArch/files/8027073/termuxarch-asus-log.txt)

**Comment by SDRausty** [comment]
Thank you for sharing the logs.  @Talmio216 this https://github.com/TermuxArch/TermuxArch/commit/6b1aaf06dc19f5b14dc6293d63d1bafbba0b3ae0 commit might resolve the USSPACE error;  Can you please check whether the installation completes as intended?
